(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 200); (Asm.Mov ((Asm.Imm 250), (Asm.Stack -108)));
       (Asm.Mov ((Asm.Imm 200), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Imm 100), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Imm 75), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Imm 25), (Asm.Stack -20)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -20)};
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -176)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -192)));
       (Asm.Mov ((Asm.Imm 7), (Asm.Stack -56)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -56)};
       (Asm.Mov ((Asm.Stack -56), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -176)));
       (Asm.Mov ((Asm.Stack -160), (Asm.Reg Asm.AX))); Asm.Cdq;
       (Asm.Idiv (Asm.Stack -176));
       (Asm.Mov ((Asm.Reg Asm.DX), (Asm.Stack -64)));
       (Asm.Mov ((Asm.Stack -64), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Stack -144), (Asm.Reg Asm.AX))); Asm.Cdq;
       (Asm.Idiv (Asm.Stack -160));
       (Asm.Mov ((Asm.Reg Asm.AX), (Asm.Stack -72)));
       (Asm.Mov ((Asm.Stack -72), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Stack -128), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -80)));
       (Asm.Mov ((Asm.Stack -80), (Asm.Reg Asm.R11)));
       Asm.Binary {op = Asm.Mult; src = (Asm.Stack -144);
         dst = (Asm.Reg Asm.R11)};
       (Asm.Mov ((Asm.Reg Asm.R11), (Asm.Stack -80)));
       (Asm.Mov ((Asm.Stack -80), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Stack -116), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -88)));
       (Asm.Mov ((Asm.Stack -128), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -88)};
       (Asm.Mov ((Asm.Stack -88), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Stack -108), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -96)));
       (Asm.Mov ((Asm.Stack -116), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -96)};
       (Asm.Mov ((Asm.Stack -96), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -108)));
       (Asm.Mov ((Asm.Stack -108), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -192)));
       (Asm.Cmp ((Asm.Imm 2250), (Asm.Stack -108)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -112)));
       (Asm.SetCC (Asm.E, (Asm.Stack -112)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -112)));
       (Asm.JmpCC (Asm.E, "and_false.17"));
       (Asm.Cmp ((Asm.Imm 2000), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -120)));
       (Asm.SetCC (Asm.E, (Asm.Stack -120)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -120)));
       (Asm.JmpCC (Asm.E, "and_false.17"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -124))); (Asm.Jmp "and_end.18");
       (Asm.Label "and_false.17"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -124)));
       (Asm.Label "and_end.18"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -124)));
       (Asm.JmpCC (Asm.E, "and_false.22"));
       (Asm.Mov ((Asm.Imm 1800), (Asm.Stack -132)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -132)};
       (Asm.Mov ((Asm.Stack -132), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.SetCC (Asm.E, (Asm.Stack -136)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.JmpCC (Asm.E, "and_false.22"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -140))); (Asm.Jmp "and_end.23");
       (Asm.Label "and_false.22"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -140)));
       (Asm.Label "and_end.23"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -140)));
       (Asm.JmpCC (Asm.E, "and_false.27"));
       (Asm.Mov ((Asm.Imm 18), (Asm.Stack -148)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -148)};
       (Asm.Mov ((Asm.Stack -148), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.SetCC (Asm.E, (Asm.Stack -152)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.JmpCC (Asm.E, "and_false.27"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -156))); (Asm.Jmp "and_end.28");
       (Asm.Label "and_false.27"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.Label "and_end.28"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Mov ((Asm.Imm 4), (Asm.Stack -164)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -164)};
       (Asm.Mov ((Asm.Stack -164), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.SetCC (Asm.E, (Asm.Stack -168)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -172))); (Asm.Jmp "and_end.33");
       (Asm.Label "and_false.32"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -172)));
       (Asm.Label "and_end.33"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -172)));
       (Asm.JmpCC (Asm.E, "and_false.37"));
       (Asm.Mov ((Asm.Imm 7), (Asm.Stack -180)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -180)};
       (Asm.Mov ((Asm.Stack -180), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -176)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -184)));
       (Asm.SetCC (Asm.E, (Asm.Stack -184)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -184)));
       (Asm.JmpCC (Asm.E, "and_false.37"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -188))); (Asm.Jmp "and_end.38");
       (Asm.Label "and_false.37"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -188)));
       (Asm.Label "and_end.38"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -188)));
       (Asm.JmpCC (Asm.E, "and_false.41"));
       (Asm.Cmp ((Asm.Imm 2250), (Asm.Stack -192)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -196)));
       (Asm.SetCC (Asm.E, (Asm.Stack -196)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -196)));
       (Asm.JmpCC (Asm.E, "and_false.41"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -200))); (Asm.Jmp "and_end.42");
       (Asm.Label "and_false.41"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -200)));
       (Asm.Label "and_end.42");
       (Asm.Mov ((Asm.Stack -200), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
