(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 188); (Asm.Mov ((Asm.Imm 11), (Asm.Stack -136)));
       (Asm.Mov ((Asm.Imm 12), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.NE, "or_true.6"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.JmpCC (Asm.NE, "or_true.6"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -20))); (Asm.Jmp "or_end.7");
       (Asm.Label "or_true.6"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -20)));
       (Asm.Label "or_end.7");
       (Asm.Mov ((Asm.Stack -136), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -24)));
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwAnd; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -24)};
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -136)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.JmpCC (Asm.NE, "or_true.10"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.NE, "or_true.10"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -40))); (Asm.Jmp "or_end.11");
       (Asm.Label "or_true.10"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -40)));
       (Asm.Label "or_end.11");
       (Asm.Mov ((Asm.Stack -144), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -44)));
       (Asm.Mov ((Asm.Stack -40), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwXor; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -44)};
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Imm 14), (Asm.Stack -156)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.JmpCC (Asm.NE, "or_true.14"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.JmpCC (Asm.NE, "or_true.14"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -68))); (Asm.Jmp "or_end.15");
       (Asm.Label "or_true.14"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -68)));
       (Asm.Label "or_end.15");
       (Asm.Mov ((Asm.Stack -156), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -72)));
       (Asm.Mov ((Asm.Stack -68), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwOr; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -72)};
       (Asm.Mov ((Asm.Stack -72), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -156)));
       (Asm.Mov ((Asm.Imm 16), (Asm.Stack -168)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.JmpCC (Asm.NE, "or_true.18"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.JmpCC (Asm.NE, "or_true.18"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -96))); (Asm.Jmp "or_end.19");
       (Asm.Label "or_true.18"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -96)));
       (Asm.Label "or_end.19");
       (Asm.Mov ((Asm.Stack -168), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -100)));
       (Asm.Mov ((Asm.Stack -96), (Asm.Reg Asm.CX)));
       (Asm.Sar ((Asm.Reg Asm.CL), (Asm.Stack -100)));
       (Asm.Mov ((Asm.Stack -100), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -168)));
       (Asm.Mov ((Asm.Imm 18), (Asm.Stack -180)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.JmpCC (Asm.NE, "or_true.22"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.JmpCC (Asm.NE, "or_true.22"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -124))); (Asm.Jmp "or_end.23");
       (Asm.Label "or_true.22"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -124)));
       (Asm.Label "or_end.23");
       (Asm.Mov ((Asm.Stack -180), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Stack -124), (Asm.Reg Asm.CX)));
       (Asm.Shl ((Asm.Reg Asm.CL), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Stack -128), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -180)));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -136)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -140)));
       (Asm.SetCC (Asm.E, (Asm.Stack -140)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -140)));
       (Asm.JmpCC (Asm.E, "and_false.28"));
       (Asm.Cmp ((Asm.Imm 13), (Asm.Stack -144)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -148)));
       (Asm.SetCC (Asm.E, (Asm.Stack -148)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -148)));
       (Asm.JmpCC (Asm.E, "and_false.28"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -152))); (Asm.Jmp "and_end.29");
       (Asm.Label "and_false.28"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.Label "and_end.29"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Cmp ((Asm.Imm 15), (Asm.Stack -156)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -160)));
       (Asm.SetCC (Asm.E, (Asm.Stack -160)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -160)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -164))); (Asm.Jmp "and_end.33");
       (Asm.Label "and_false.32"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -164)));
       (Asm.Label "and_end.33"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -164)));
       (Asm.JmpCC (Asm.E, "and_false.36"));
       (Asm.Cmp ((Asm.Imm 8), (Asm.Stack -168)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -172)));
       (Asm.SetCC (Asm.E, (Asm.Stack -172)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -172)));
       (Asm.JmpCC (Asm.E, "and_false.36"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -176))); (Asm.Jmp "and_end.37");
       (Asm.Label "and_false.36"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -176)));
       (Asm.Label "and_end.37"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -176)));
       (Asm.JmpCC (Asm.E, "and_false.40"));
       (Asm.Cmp ((Asm.Imm 36), (Asm.Stack -180)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -184)));
       (Asm.SetCC (Asm.E, (Asm.Stack -184)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -184)));
       (Asm.JmpCC (Asm.E, "and_false.40"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -188))); (Asm.Jmp "and_end.41");
       (Asm.Label "and_false.40"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -188)));
       (Asm.Label "and_end.41");
       (Asm.Mov ((Asm.Stack -188), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
