(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 148); (Asm.Mov ((Asm.Imm 10), (Asm.Stack -108)));
       (Asm.Mov ((Asm.Imm 12), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.NE, "or_true.5"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -116)));
       (Asm.JmpCC (Asm.NE, "or_true.5"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -20))); (Asm.Jmp "or_end.6");
       (Asm.Label "or_true.5"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -20)));
       (Asm.Label "or_end.6");
       (Asm.Mov ((Asm.Stack -108), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -24)));
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -24)};
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -108)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -108)));
       (Asm.JmpCC (Asm.E, "and_false.9"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "and_false.9"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -40))); (Asm.Jmp "and_end.10");
       (Asm.Label "and_false.9"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.Label "and_end.10");
       (Asm.Mov ((Asm.Stack -116), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -44)));
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.R11)));
       Asm.Binary {op = Asm.Mult; src = (Asm.Stack -40);
         dst = (Asm.Reg Asm.R11)};
       (Asm.Mov ((Asm.Reg Asm.R11), (Asm.Stack -44)));
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Imm 14), (Asm.Stack -128)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -108)));
       (Asm.JmpCC (Asm.NE, "or_true.13"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -116)));
       (Asm.JmpCC (Asm.NE, "or_true.13"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -68))); (Asm.Jmp "or_end.14");
       (Asm.Label "or_true.13"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -68)));
       (Asm.Label "or_end.14");
       (Asm.Mov ((Asm.Stack -128), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -72)));
       (Asm.Mov ((Asm.Stack -68), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -72)};
       (Asm.Mov ((Asm.Stack -72), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Imm 16), (Asm.Stack -140)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -128)));
       (Asm.JmpCC (Asm.NE, "or_true.17"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -140)));
       (Asm.JmpCC (Asm.NE, "or_true.17"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -96))); (Asm.Jmp "or_end.18");
       (Asm.Label "or_true.17"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -96)));
       (Asm.Label "or_end.18");
       (Asm.Mov ((Asm.Stack -140), (Asm.Reg Asm.AX))); Asm.Cdq;
       (Asm.Idiv (Asm.Stack -96));
       (Asm.Mov ((Asm.Reg Asm.AX), (Asm.Stack -100)));
       (Asm.Mov ((Asm.Stack -100), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -140)));
       (Asm.Cmp ((Asm.Imm 11), (Asm.Stack -108)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -112)));
       (Asm.SetCC (Asm.E, (Asm.Stack -112)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -112)));
       (Asm.JmpCC (Asm.E, "and_false.23"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -116)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -120)));
       (Asm.SetCC (Asm.E, (Asm.Stack -120)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -120)));
       (Asm.JmpCC (Asm.E, "and_false.23"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -124))); (Asm.Jmp "and_end.24");
       (Asm.Label "and_false.23"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -124)));
       (Asm.Label "and_end.24"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -124)));
       (Asm.JmpCC (Asm.E, "and_false.27"));
       (Asm.Cmp ((Asm.Imm 13), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -132)));
       (Asm.SetCC (Asm.E, (Asm.Stack -132)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -132)));
       (Asm.JmpCC (Asm.E, "and_false.27"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -136))); (Asm.Jmp "and_end.28");
       (Asm.Label "and_false.27"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.Label "and_end.28"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -136)));
       (Asm.JmpCC (Asm.E, "and_false.31"));
       (Asm.Cmp ((Asm.Imm 16), (Asm.Stack -140)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.SetCC (Asm.E, (Asm.Stack -144)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.JmpCC (Asm.E, "and_false.31"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -148))); (Asm.Jmp "and_end.32");
       (Asm.Label "and_false.31"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -148)));
       (Asm.Label "and_end.32");
       (Asm.Mov ((Asm.Stack -148), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
