(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 252); (Asm.Mov ((Asm.Imm 250), (Asm.Stack -140)));
       (Asm.Mov ((Asm.Imm 200), (Asm.Stack -148)));
       (Asm.Mov ((Asm.Imm 100), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Imm 75), (Asm.Stack -172)));
       (Asm.Mov ((Asm.Imm 50), (Asm.Stack -184)));
       (Asm.Mov ((Asm.Imm 25), (Asm.Stack -196)));
       (Asm.Mov ((Asm.Imm 10), (Asm.Stack -208)));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -220)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -232)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -244)));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -232)));
       (Asm.Mov ((Asm.Stack -220), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -76)));
       (Asm.Mov ((Asm.Stack -232), (Asm.Reg Asm.CX)));
       (Asm.Shl ((Asm.Reg Asm.CL), (Asm.Stack -76)));
       (Asm.Mov ((Asm.Stack -76), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -220)));
       (Asm.Mov ((Asm.Stack -208), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -84)));
       (Asm.Mov ((Asm.Stack -220), (Asm.Reg Asm.CX)));
       (Asm.Sar ((Asm.Reg Asm.CL), (Asm.Stack -84)));
       (Asm.Mov ((Asm.Stack -84), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -208)));
       (Asm.Mov ((Asm.Stack -196), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -92)));
       (Asm.Mov ((Asm.Stack -208), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -92)};
       (Asm.Mov ((Asm.Stack -92), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -196)));
       (Asm.Mov ((Asm.Stack -184), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -100)));
       (Asm.Mov ((Asm.Stack -196), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwXor; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -100)};
       (Asm.Mov ((Asm.Stack -100), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -184)));
       (Asm.Mov ((Asm.Stack -184), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -172)));
       (Asm.Mov ((Asm.Stack -160), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -112)));
       (Asm.Mov ((Asm.Stack -172), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwOr; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -112)};
       (Asm.Mov ((Asm.Stack -112), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Stack -148), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -120)));
       (Asm.Mov ((Asm.Stack -120), (Asm.Reg Asm.R11)));
       Asm.Binary {op = Asm.Mult; src = (Asm.Stack -160);
         dst = (Asm.Reg Asm.R11)};
       (Asm.Mov ((Asm.Reg Asm.R11), (Asm.Stack -120)));
       (Asm.Mov ((Asm.Stack -120), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -148)));
       (Asm.Mov ((Asm.Stack -140), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -128)));
       (Asm.Mov ((Asm.Stack -148), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.BwAnd; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -128)};
       (Asm.Mov ((Asm.Stack -128), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -140)));
       (Asm.Mov ((Asm.Stack -140), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -244)));
       (Asm.Cmp ((Asm.Imm 40), (Asm.Stack -140)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.SetCC (Asm.E, (Asm.Stack -144)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -144)));
       (Asm.JmpCC (Asm.E, "and_false.20"));
       (Asm.Cmp ((Asm.Imm 21800), (Asm.Stack -148)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.SetCC (Asm.E, (Asm.Stack -152)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -152)));
       (Asm.JmpCC (Asm.E, "and_false.20"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -156))); (Asm.Jmp "and_end.21");
       (Asm.Label "and_false.20"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.Label "and_end.21"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -156)));
       (Asm.JmpCC (Asm.E, "and_false.24"));
       (Asm.Cmp ((Asm.Imm 109), (Asm.Stack -160)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -164)));
       (Asm.SetCC (Asm.E, (Asm.Stack -164)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -164)));
       (Asm.JmpCC (Asm.E, "and_false.24"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -168))); (Asm.Jmp "and_end.25");
       (Asm.Label "and_false.24"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.Label "and_end.25"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -168)));
       (Asm.JmpCC (Asm.E, "and_false.28"));
       (Asm.Cmp ((Asm.Imm 41), (Asm.Stack -172)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -176)));
       (Asm.SetCC (Asm.E, (Asm.Stack -176)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -176)));
       (Asm.JmpCC (Asm.E, "and_false.28"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -180))); (Asm.Jmp "and_end.29");
       (Asm.Label "and_false.28"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -180)));
       (Asm.Label "and_end.29"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -180)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Cmp ((Asm.Imm 41), (Asm.Stack -184)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -188)));
       (Asm.SetCC (Asm.E, (Asm.Stack -188)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -188)));
       (Asm.JmpCC (Asm.E, "and_false.32"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -192))); (Asm.Jmp "and_end.33");
       (Asm.Label "and_false.32"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -192)));
       (Asm.Label "and_end.33"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -192)));
       (Asm.JmpCC (Asm.E, "and_false.36"));
       (Asm.Cmp ((Asm.Imm 27), (Asm.Stack -196)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -200)));
       (Asm.SetCC (Asm.E, (Asm.Stack -200)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -200)));
       (Asm.JmpCC (Asm.E, "and_false.36"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -204))); (Asm.Jmp "and_end.37");
       (Asm.Label "and_false.36"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -204)));
       (Asm.Label "and_end.37"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -204)));
       (Asm.JmpCC (Asm.E, "and_false.40"));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -208)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -212)));
       (Asm.SetCC (Asm.E, (Asm.Stack -212)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -212)));
       (Asm.JmpCC (Asm.E, "and_false.40"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -216))); (Asm.Jmp "and_end.41");
       (Asm.Label "and_false.40"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -216)));
       (Asm.Label "and_end.41"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -216)));
       (Asm.JmpCC (Asm.E, "and_false.44"));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -220)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -224)));
       (Asm.SetCC (Asm.E, (Asm.Stack -224)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -224)));
       (Asm.JmpCC (Asm.E, "and_false.44"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -228))); (Asm.Jmp "and_end.45");
       (Asm.Label "and_false.44"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -228)));
       (Asm.Label "and_end.45"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -228)));
       (Asm.JmpCC (Asm.E, "and_false.48"));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -232)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -236)));
       (Asm.SetCC (Asm.E, (Asm.Stack -236)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -236)));
       (Asm.JmpCC (Asm.E, "and_false.48"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -240))); (Asm.Jmp "and_end.49");
       (Asm.Label "and_false.48"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -240)));
       (Asm.Label "and_end.49"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -240)));
       (Asm.JmpCC (Asm.E, "and_false.52"));
       (Asm.Cmp ((Asm.Imm 40), (Asm.Stack -244)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -248)));
       (Asm.SetCC (Asm.E, (Asm.Stack -248)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -248)));
       (Asm.JmpCC (Asm.E, "and_false.52"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -252))); (Asm.Jmp "and_end.53");
       (Asm.Label "and_false.52"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -252)));
       (Asm.Label "and_end.53");
       (Asm.Mov ((Asm.Stack -252), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
