(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 76); (Asm.Mov ((Asm.Imm 10), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 12), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.NE, "or.tr.1"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.JmpCC (Asm.NE, "or.tr.1"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -12))); (Asm.Jmp "or.en.2");
       (Asm.Label "or.tr.1"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -12)));
       (Asm.Label "or.en.2"); (Asm.Mov ((Asm.Stack -4), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -16)));
       (Asm.Mov ((Asm.Stack -12), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -16)};
       (Asm.Mov ((Asm.Stack -16), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -4)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -4)));
       (Asm.JmpCC (Asm.E, "and.fl.5"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "and.fl.5"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -20))); (Asm.Jmp "and.en.6");
       (Asm.Label "and.fl.5"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -20)));
       (Asm.Label "and.en.6"); (Asm.Mov ((Asm.Stack -8), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -24)));
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R11)));
       Asm.Binary {op = Asm.Mult; src = (Asm.Stack -20);
         dst = (Asm.Reg Asm.R11)};
       (Asm.Mov ((Asm.Reg Asm.R11), (Asm.Stack -24)));
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 14), (Asm.Stack -28)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -4)));
       (Asm.JmpCC (Asm.NE, "or.tr.9"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.JmpCC (Asm.NE, "or.tr.9"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32))); (Asm.Jmp "or.en.10");
       (Asm.Label "or.tr.9"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -32)));
       (Asm.Label "or.en.10");
       (Asm.Mov ((Asm.Stack -28), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -36)));
       (Asm.Mov ((Asm.Stack -32), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -36)};
       (Asm.Mov ((Asm.Stack -36), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Imm 16), (Asm.Stack -40)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.JmpCC (Asm.NE, "or.tr.13"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.JmpCC (Asm.NE, "or.tr.13"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -44))); (Asm.Jmp "or.en.14");
       (Asm.Label "or.tr.13"); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -44)));
       (Asm.Label "or.en.14"); (Asm.Mov ((Asm.Stack -40), (Asm.Reg Asm.AX)));
       Asm.Cdq; (Asm.Idiv (Asm.Stack -44));
       (Asm.Mov ((Asm.Reg Asm.AX), (Asm.Stack -48)));
       (Asm.Mov ((Asm.Stack -48), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -40)));
       (Asm.Cmp ((Asm.Imm 11), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.SetCC (Asm.E, (Asm.Stack -52)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.JmpCC (Asm.E, "and.fl.19"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.SetCC (Asm.E, (Asm.Stack -56)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.JmpCC (Asm.E, "and.fl.19"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -60))); (Asm.Jmp "and.en.20");
       (Asm.Label "and.fl.19"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -60)));
       (Asm.Label "and.en.20"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -60)));
       (Asm.JmpCC (Asm.E, "and.fl.23"));
       (Asm.Cmp ((Asm.Imm 13), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -64)));
       (Asm.SetCC (Asm.E, (Asm.Stack -64)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -64)));
       (Asm.JmpCC (Asm.E, "and.fl.23"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -68))); (Asm.Jmp "and.en.24");
       (Asm.Label "and.fl.23"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -68)));
       (Asm.Label "and.en.24"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -68)));
       (Asm.JmpCC (Asm.E, "and.fl.27"));
       (Asm.Cmp ((Asm.Imm 16), (Asm.Stack -40)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.SetCC (Asm.E, (Asm.Stack -72)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.JmpCC (Asm.E, "and.fl.27"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -76))); (Asm.Jmp "and.en.28");
       (Asm.Label "and.fl.27"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -76)));
       (Asm.Label "and.en.28");
       (Asm.Mov ((Asm.Stack -76), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
