(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 84); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -40)));
       (Asm.Mov ((Asm.Imm 2), (Asm.Stack -48)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -40)};
       (Asm.Mov ((Asm.Stack -40), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -16)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -16)};
       (Asm.Mov ((Asm.Stack -16), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -60)));
       (Asm.Mov ((Asm.Stack -48), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -28)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Imm 1); dst = (Asm.Stack -48)};
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.SetCC (Asm.E, (Asm.Stack -32)));
       (Asm.Mov ((Asm.Stack -32), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -76)));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -40)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.SetCC (Asm.E, (Asm.Stack -44)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.JmpCC (Asm.E, "and_false.10"));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -48)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.SetCC (Asm.E, (Asm.Stack -52)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.JmpCC (Asm.E, "and_false.10"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -56))); (Asm.Jmp "and_end.11");
       (Asm.Label "and_false.10"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.Label "and_end.11"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.JmpCC (Asm.E, "and_false.15"));
       (Asm.Mov ((Asm.Imm 2), (Asm.Stack -64)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -64)};
       (Asm.Mov ((Asm.Stack -64), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -60)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -68)));
       (Asm.SetCC (Asm.E, (Asm.Stack -68)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -68)));
       (Asm.JmpCC (Asm.E, "and_false.15"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -72))); (Asm.Jmp "and_end.16");
       (Asm.Label "and_false.15"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.Label "and_end.16"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.JmpCC (Asm.E, "and_false.19"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -76)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -80)));
       (Asm.SetCC (Asm.E, (Asm.Stack -80)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -80)));
       (Asm.JmpCC (Asm.E, "and_false.19"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -84))); (Asm.Jmp "and_end.20");
       (Asm.Label "and_false.19"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -84)));
       (Asm.Label "and_end.20");
       (Asm.Mov ((Asm.Stack -84), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
