(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 44); (Asm.Mov ((Asm.Imm 2), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Stack -4), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -12)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -4)};
       (Asm.Mov ((Asm.Imm 3), (Asm.Stack -16)));
       (Asm.Mov ((Asm.Stack -12), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -16)};
       (Asm.Mov ((Asm.Stack -16), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -8)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -8)};
       (Asm.Mov ((Asm.Imm 4), (Asm.Stack -24)));
       (Asm.Mov ((Asm.Stack -8), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Add; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -24)};
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -20)));
       (Asm.Cmp ((Asm.Imm 3), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.SetCC (Asm.E, (Asm.Stack -28)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.JmpCC (Asm.E, "and_false.9"));
       (Asm.Cmp ((Asm.Imm 6), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.SetCC (Asm.E, (Asm.Stack -32)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.JmpCC (Asm.E, "and_false.9"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -36))); (Asm.Jmp "and_end.10");
       (Asm.Label "and_false.9"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.Label "and_end.10"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.JmpCC (Asm.E, "and_false.13"));
       (Asm.Cmp ((Asm.Imm 10), (Asm.Stack -20)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.SetCC (Asm.E, (Asm.Stack -40)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.JmpCC (Asm.E, "and_false.13"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -44))); (Asm.Jmp "and_end.14");
       (Asm.Label "and_false.13"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.Label "and_end.14");
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
