(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 88); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -44)));
       (Asm.Mov ((Asm.Imm 2), (Asm.Stack -52)));
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -16)));
       (Asm.Mov ((Asm.Stack -16), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -44)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -44)};
       (Asm.Mov ((Asm.Stack -44), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -20)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -20)};
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -64)));
       (Asm.Mov ((Asm.Stack -52), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -32)));
       (Asm.Mov ((Asm.Stack -32), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -52)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Imm 1); dst = (Asm.Stack -52)};
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.SetCC (Asm.E, (Asm.Stack -36)));
       (Asm.Mov ((Asm.Stack -36), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -80)));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -44)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -48)));
       (Asm.SetCC (Asm.E, (Asm.Stack -48)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -48)));
       (Asm.JmpCC (Asm.E, "and_false.11"));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -52)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.SetCC (Asm.E, (Asm.Stack -56)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.JmpCC (Asm.E, "and_false.11"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -60))); (Asm.Jmp "and_end.12");
       (Asm.Label "and_false.11"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -60)));
       (Asm.Label "and_end.12"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -60)));
       (Asm.JmpCC (Asm.E, "and_false.16"));
       (Asm.Mov ((Asm.Imm 2), (Asm.Stack -68)));
       Asm.Unary {op = Asm.Neg; dst = (Asm.Stack -68)};
       (Asm.Mov ((Asm.Stack -68), (Asm.Reg Asm.R10)));
       (Asm.Cmp ((Asm.Reg Asm.R10), (Asm.Stack -64)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.SetCC (Asm.E, (Asm.Stack -72)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -72)));
       (Asm.JmpCC (Asm.E, "and_false.16"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -76))); (Asm.Jmp "and_end.17");
       (Asm.Label "and_false.16"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -76)));
       (Asm.Label "and_end.17"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -76)));
       (Asm.JmpCC (Asm.E, "and_false.20"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -80)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -84)));
       (Asm.SetCC (Asm.E, (Asm.Stack -84)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -84)));
       (Asm.JmpCC (Asm.E, "and_false.20"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -88))); (Asm.Jmp "and_end.21");
       (Asm.Label "and_false.20"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -88)));
       (Asm.Label "and_end.21");
       (Asm.Mov ((Asm.Stack -88), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
