(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 68); (Asm.Mov ((Asm.Imm 1), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Imm 2), (Asm.Stack -36)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -28)};
       (Asm.Mov ((Asm.Stack -28), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -48)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Imm 1); dst = (Asm.Stack -36)};
       (Asm.Mov ((Asm.Stack -36), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -60)));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.SetCC (Asm.E, (Asm.Stack -32)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.JmpCC (Asm.E, "and_false.7"));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -36)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.SetCC (Asm.E, (Asm.Stack -40)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -40)));
       (Asm.JmpCC (Asm.E, "and_false.7"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -44))); (Asm.Jmp "and_end.8");
       (Asm.Label "and_false.7"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.Label "and_end.8"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.JmpCC (Asm.E, "and_false.11"));
       (Asm.Cmp ((Asm.Imm 2), (Asm.Stack -48)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.SetCC (Asm.E, (Asm.Stack -52)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.JmpCC (Asm.E, "and_false.11"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -56))); (Asm.Jmp "and_end.12");
       (Asm.Label "and_false.11"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.Label "and_end.12"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.JmpCC (Asm.E, "and_false.15"));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Stack -60)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -64)));
       (Asm.SetCC (Asm.E, (Asm.Stack -64)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -64)));
       (Asm.JmpCC (Asm.E, "and_false.15"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -68))); (Asm.Jmp "and_end.16");
       (Asm.Label "and_false.15"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -68)));
       (Asm.Label "and_end.16");
       (Asm.Mov ((Asm.Stack -68), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
