(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 36); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 100), (Asm.Stack -8))); (Asm.Label "loop.ct.1");
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.JmpCC (Asm.E, "loop.br.1"));
       (Asm.Mov ((Asm.Imm 10), (Asm.Stack -12)));
       (Asm.Mov ((Asm.Stack -8), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -16)));
       (Asm.Mov ((Asm.Stack -12), (Asm.Reg Asm.R10)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Reg Asm.R10);
         dst = (Asm.Stack -16)};
       (Asm.Mov ((Asm.Stack -16), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -8)));
       (Asm.Label "loop.ct.2"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -12)));
       (Asm.JmpCC (Asm.E, "loop.br.2"));
       (Asm.Mov ((Asm.Stack -4), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -20)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -20)};
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Stack -12), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -24)));
       Asm.Binary {op = Asm.Sub; src = (Asm.Imm 1); dst = (Asm.Stack -24)};
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -12))); (Asm.Jmp "loop.ct.2");
       (Asm.Label "loop.br.2"); (Asm.Jmp "loop.ct.1");
       (Asm.Label "loop.br.1"); (Asm.Cmp ((Asm.Imm 100), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.SetCC (Asm.E, (Asm.Stack -28)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.JmpCC (Asm.E, "and_false.6"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.SetCC (Asm.E, (Asm.Stack -32)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.JmpCC (Asm.E, "and_false.6"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -36))); (Asm.Jmp "and_end.7");
       (Asm.Label "and_false.6"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.Label "and_end.7");
       (Asm.Mov ((Asm.Stack -36), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
