(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 56); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -12)));
       (Asm.Mov ((Asm.Imm 3), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -16)));
       (Asm.SetCC (Asm.E, (Asm.Stack -16)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -16)));
       (Asm.JmpCC (Asm.NE, "swit.cs.1.0"));
       (Asm.Mov ((Asm.Imm 3), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 1), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -20)));
       (Asm.SetCC (Asm.E, (Asm.Stack -20)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -20)));
       (Asm.JmpCC (Asm.NE, "swit.cs.1.1"));
       (Asm.Mov ((Asm.Imm 3), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 3), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -24)));
       (Asm.SetCC (Asm.E, (Asm.Stack -24)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -24)));
       (Asm.JmpCC (Asm.NE, "swit.cs.1.3")); (Asm.Jmp "swit.df.1");
       (Asm.Label "swit.cs.1.0"); (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX)));
       Asm.Ret; (Asm.Label "swit.cs.1.1");
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "if.en.3")); (Asm.Label "swit.cs.1.3");
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -4))); (Asm.Jmp "swit.br.1");
       (Asm.Label "if.en.3"); (Asm.Label "swit.df.1");
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Label "swit.br.1"); (Asm.Mov ((Asm.Imm 4), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.SetCC (Asm.E, (Asm.Stack -28)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -28)));
       (Asm.JmpCC (Asm.NE, "swit.cs.2.0"));
       (Asm.Mov ((Asm.Imm 4), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 4), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.SetCC (Asm.E, (Asm.Stack -32)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -32)));
       (Asm.JmpCC (Asm.NE, "swit.cs.2.4")); (Asm.Jmp "swit.df.2");
       (Asm.Label "swit.cs.2.0"); (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX)));
       Asm.Ret; (Asm.Mov ((Asm.Imm 1), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "if.el.7"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Jmp "if.en.6"); (Asm.Label "if.el.7"); (Asm.Label "swit.cs.2.4");
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -8))); (Asm.Jmp "swit.br.2");
       (Asm.Label "if.en.6"); (Asm.Label "swit.df.2");
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Label "swit.br.2"); (Asm.Mov ((Asm.Imm 5), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 5), (Asm.Reg Asm.R11)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.SetCC (Asm.E, (Asm.Stack -36)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -36)));
       (Asm.JmpCC (Asm.NE, "swit.cs.3.5")); (Asm.Jmp "swit.df.3");
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -40))); (Asm.Label "loop.st.4");
       (Asm.Cmp ((Asm.Imm 10), (Asm.Stack -40)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.SetCC (Asm.L, (Asm.Stack -44)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -44)));
       (Asm.JmpCC (Asm.E, "loop.br.4"));
       (Asm.Mov ((Asm.Imm 0), (Asm.Stack -4))); (Asm.Label "swit.cs.3.5");
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -12))); (Asm.Jmp "loop.br.4");
       (Asm.Label "swit.df.3"); (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX)));
       Asm.Ret; (Asm.Label "loop.ct.4");
       (Asm.Mov ((Asm.Stack -40), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -48)));
       Asm.Binary {op = Asm.Add; src = (Asm.Imm 1); dst = (Asm.Stack -48)};
       (Asm.Mov ((Asm.Stack -48), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -40))); (Asm.Jmp "loop.st.4");
       (Asm.Label "loop.br.4"); (Asm.Label "swit.br.3");
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -4)));
       (Asm.JmpCC (Asm.E, "and.fl.12"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -8)));
       (Asm.JmpCC (Asm.E, "and.fl.12"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -52))); (Asm.Jmp "and.en.13");
       (Asm.Label "and.fl.12"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.Label "and.en.13"); (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -52)));
       (Asm.JmpCC (Asm.E, "and.fl.15"));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Stack -12)));
       (Asm.JmpCC (Asm.E, "and.fl.15"));
       (Asm.Mov ((Asm.Imm 1), (Asm.Stack -56))); (Asm.Jmp "and.en.16");
       (Asm.Label "and.fl.15"); (Asm.Mov ((Asm.Imm 0), (Asm.Stack -56)));
       (Asm.Label "and.en.16");
       (Asm.Mov ((Asm.Stack -56), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
