(Asm.Program
   Asm.Function {name = "main";
     instructions =
     [(Asm.AllocateStack 28); (Asm.Mov ((Asm.Imm 1), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "cond_e2.2"));
       (Asm.Mov ((Asm.Imm 2), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "cond_e2.5"));
       (Asm.Mov ((Asm.Imm 3), (Asm.Stack -12))); (Asm.Jmp "cond_end.4");
       (Asm.Label "cond_e2.5"); (Asm.Mov ((Asm.Imm 4), (Asm.Stack -12)));
       (Asm.Label "cond_end.4");
       (Asm.Mov ((Asm.Stack -12), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -8))); (Asm.Jmp "cond_end.1");
       (Asm.Label "cond_e2.2"); (Asm.Mov ((Asm.Imm 5), (Asm.Stack -8)));
       (Asm.Label "cond_end.1");
       (Asm.Mov ((Asm.Stack -8), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -4)));
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "cond_e2.8"));
       (Asm.Mov ((Asm.Imm 2), (Asm.Reg Asm.R11)));
       (Asm.Cmp ((Asm.Imm 0), (Asm.Reg Asm.R11)));
       (Asm.JmpCC (Asm.E, "cond_e2.11"));
       (Asm.Mov ((Asm.Imm 3), (Asm.Stack -24))); (Asm.Jmp "cond_end.10");
       (Asm.Label "cond_e2.11"); (Asm.Mov ((Asm.Imm 4), (Asm.Stack -24)));
       (Asm.Label "cond_end.10");
       (Asm.Mov ((Asm.Stack -24), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -20)));
       (Asm.Jmp "cond_end.7"); (Asm.Label "cond_e2.8");
       (Asm.Mov ((Asm.Imm 5), (Asm.Stack -20))); (Asm.Label "cond_end.7");
       (Asm.Mov ((Asm.Stack -20), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -16)));
       (Asm.Mov ((Asm.Stack -4), (Asm.Reg Asm.R10)));
       (Asm.Mov ((Asm.Reg Asm.R10), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Stack -28), (Asm.Reg Asm.R11)));
       Asm.Binary {op = Asm.Mult; src = (Asm.Stack -16);
         dst = (Asm.Reg Asm.R11)};
       (Asm.Mov ((Asm.Reg Asm.R11), (Asm.Stack -28)));
       (Asm.Mov ((Asm.Stack -28), (Asm.Reg Asm.AX))); Asm.Ret;
       (Asm.Mov ((Asm.Imm 0), (Asm.Reg Asm.AX))); Asm.Ret]})
